[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["Bhavani Shankar <ebhavanishankar@gmail.com>"]
edition = "2018"

[dependencies]
aoc-runner = "0.3"
aoc-runner-derive = "0.3"
fnv = "1.0.7"
parse-display = "0.4"
itertools = "0.9"
